"""Hand-checked links from ingredient names to foods.

Keys are lowercase ingredient names as recipes write them. Values are an exact
USDA FoodData Central description, or the name of a CUSTOM food below. Names
missing here are left unmatched (shown in the app for a manual pick).
"""

# Foods USDA doesn't have. Per 100 g: kcal, protein, fat, carbs (approximate,
# from typical product labels).
CUSTOM = {
    "MSG": (0, 0, 0, 0),
    "Gochujang": (210, 5, 1.5, 45),
    "Mirin": (240, 0.3, 0, 43),
    "Za'atar": (300, 10, 15, 45),
    "Mexican crema": (330, 2, 33, 4),
    "Sumac": (240, 4, 14, 38),
    "Harissa paste": (110, 3, 7, 11),
    "Chili crisp": (650, 3, 65, 12),
    "Chipotles in adobo": (80, 2, 3, 12),
    "Kewpie mayonnaise": (700, 2.5, 76, 1),
    "Garam masala": (380, 14, 15, 50),
    "Hot sauce": (12, 0.5, 0.4, 2),
    "Chinese black vinegar": (50, 1, 0, 10),
    "Rice vinegar": (18, 0, 0, 4),
    "Shaoxing wine": (130, 1.6, 0, 5),
    "Chinese chili flakes": (320, 12, 17, 50),
    "Aleppo pepper": (320, 12, 14, 55),
    "Calabrian chilies in oil": (330, 2, 33, 7),
    "Parmigiano Reggiano": (390, 33, 28, 0),
    "Pecorino Romano": (390, 32, 27, 3),
    "Brioche bun": (310, 9, 8, 50),
    "Hoagie roll": (270, 9, 3.5, 50),
    "Chicken bouillon paste": (180, 7, 9, 18),
    "Beef bouillon paste": (180, 8, 8, 20),
    "Lavash": (275, 9, 1.5, 56),
    "Naan": (290, 9, 6, 50),
    "Paratha": (330, 7, 13, 46),
    "Roti": (300, 9, 7, 50),
    "Gyoza wrappers": (280, 8, 1, 58),
    "Rice paper": (330, 0, 0, 83),
    "Ramen noodles, fresh": (290, 10, 2, 57),
    "Instant ramen": (440, 9, 17, 62),
    "Lo mein noodles": (290, 10, 2, 57),
    "Kimchi": (23, 1.1, 0.5, 4),
    "Paneer": (320, 20, 25, 3),
    "Beef tallow": (900, 0, 100, 0),
    "Chorizo, Mexican raw": (340, 16, 29, 2),
    "Prosciutto": (250, 26, 16, 0),
    "Guanciale": (650, 7, 70, 0),
    "Mortadella": (310, 16, 25, 3),
    "Soppressata": (400, 25, 33, 2),
    "Potato starch": (330, 0.1, 0, 83),
    "Panko": (380, 12, 3, 78),
    "Tahini": (595, 17, 54, 21),
    "Coconut milk, canned": (200, 2, 21, 3),
    "Salsa": (35, 1.5, 0.2, 7),
    "Pico de gallo": (20, 0.8, 0.2, 4.5),
    "Refried beans": (90, 5, 1.5, 15),
    "Frozen french fries": (150, 2.3, 5, 24),
    "Fish sauce": (35, 5, 0, 4),
    "Oyster sauce": (51, 1.4, 0.3, 11),
    "Chili garlic sauce": (100, 2, 2, 17),
    "Red curry paste": (160, 3, 7, 20),
    "Massaman curry paste": (270, 4, 17, 25),
    "Japanese curry roux": (510, 6, 34, 45),
    "Achiote paste": (200, 3, 5, 35),
    "Miso paste": (200, 12, 6, 26),
    "Ponzu": (60, 3, 0, 10),
    "Maggi seasoning": (90, 10, 0, 12),
    "Tonkatsu sauce": (130, 1, 0, 30),
    "Black pepper sauce": (110, 2, 2, 20),
    "Chili oil with fermented soybeans": (650, 5, 65, 10),
    "Pomegranate molasses": (270, 0.5, 0, 67),
    "Dashi powder": (220, 25, 1, 30),
    "Furikake": (400, 15, 25, 35),
    "Bonito flakes": (340, 77, 3, 0),
    "Shokupan": (270, 9, 5, 48),
    "Gnocchi, shelf-stable": (160, 4, 0.5, 34),
    "Tteok (rice cakes)": (230, 4, 0.5, 52),
    "Low-fat American cheese": (190, 20, 7, 10),
    "Low-carb tortilla": (180, 15, 6, 40),
    "High-protein tortilla": (260, 20, 7, 38),
    "Cheese sauce (Cheez Whiz)": (270, 11, 21, 9),
    "Cajun seasoning": (250, 8, 5, 45),
    "Taco seasoning": (300, 7, 5, 55),
    "Protein bar": (380, 33, 13, 38),
    "Better Than Bouillon, mushroom": (200, 5, 8, 25),
    "Bao bun": (230, 6, 3, 45),
    "Arepa de choclo": (230, 5, 7, 38),
    "Queso de freir": (320, 20, 25, 3),
    "Mexican manchego": (380, 24, 31, 1),
    "Diastatic malt powder": (360, 10, 2, 78),
    "Xanthan gum": (330, 0, 0, 80),
    "Kasoori methi": (320, 23, 6, 58),
    "Browning sauce": (230, 0, 0, 58),
    "Muhammara": (300, 5, 25, 15),
    "Tamarind puree": (240, 2.8, 0.6, 62),
    "Palm sugar": (380, 0, 0, 97),
    "Coconut powder, toasted": (660, 7, 65, 24),
    "Onion confit": (200, 1, 8, 30),
    "Hot pepper spread": (200, 1, 18, 8),
    "Roasted red pepper condiment": (40, 1, 1, 7),
    "Crayfish powder": (330, 60, 8, 3),
    "Beef short ribs": (390, 16, 36, 0),
    "Crystallized ginger": (350, 0.2, 0.2, 87),
}

FOOD_FOR = {
    # zero-calorie
    "water": "Water, bottled, generic", "ice water": "Water, bottled, generic",
    "ice cubes": "Water, bottled, generic", "pasta water": "Water, bottled, generic",
    "salt": "Salt, table", "kosher salt": "Salt, table", "flaky salt": "Salt, table",
    "msg": "MSG",
    # oils and fats
    "cooking oil": "Oil, canola", "neutral oil": "Oil, canola", "canola oil": "Oil, canola",
    "olive oil": "Oil, olive, salad or cooking", "extra virgin olive oil": "Oil, olive, salad or cooking",
    "sesame oil": "Oil, sesame, salad or cooking", "toasted sesame oil": "Oil, sesame, salad or cooking",
    "peanut oil": "Oil, peanut, salad or cooking", "mustard oil": "Oil, mustard",
    "baking spray": "Oil, canola", "non stick cooking spray": "Oil, canola", "flavored oils": "Oil, olive, salad or cooking",
    "butter": "Butter, salted", "ghee": "Butter oil, anhydrous", "lard": "Lard", "beef tallow": "Beef tallow",
    "chili crisp oil": "Chili crisp", "chili oil w/ fermented soybeans": "Chili oil with fermented soybeans",
    # alliums, aromatics
    "garlic": "Garlic, raw", "onions": "Onions, raw", "yellow onion": "Onions, raw", "sweet onion": "Onions, sweet, raw",
    "red onions": "Onions, raw", "white onions": "Onions, raw", "pickled onions": "Onions, raw",
    "shallots": "Shallots, raw", "scallions": "Onions, spring or scallions (includes tops and bulb), raw",
    "chives": "Chives, raw", "chinese chives": "Chives, raw", "leeks": "Leeks, (bulb and lower leaf-portion), raw",
    "fresh ginger": "Ginger root, raw", "galangal root": "Ginger root, raw", "lemongrass": "Lemon grass (citronella), raw",
    "pickled ginger": "Ginger root, pickled, canned, with artificial sweetener", "candied ginger": "Crystallized ginger",
    "horseradish root": "Horseradish, prepared", "horseradish condiment": "Horseradish, prepared",
    # herbs
    "cilantro": "Coriander (cilantro) leaves, raw", "parsley": "Parsley, fresh", "fresh basil": "Basil, fresh",
    "thai basil": "Basil, fresh", "fresh mint": "Spearmint, fresh", "fresh dill": "Dill weed, fresh", "dill": "Dill weed, fresh",
    "rosemary": "Rosemary, fresh", "fresh rosemary": "Rosemary, fresh", "thyme": "Thyme, fresh", "fresh thyme": "Thyme, fresh",
    "fresh oregano": "Spices, oregano, dried", "fresh sage": "Spices, sage, ground", "herbs": "Parsley, fresh",
    "makrut lime leaves": "Coriander (cilantro) leaves, raw", "epazote": "Epazote, raw", "epazote leaves": "Epazote, raw",
    "fenugreek leaves": "Coriander (cilantro) leaves, raw", "kasoori methi": "Kasoori methi",
    # dried spices
    "black pepper": "Spices, pepper, black", "white pepper": "Spices, pepper, white", "peppercorns": "Spices, pepper, black",
    "black peppercorns": "Spices, pepper, black", "szechuan peppercorns": "Spices, pepper, black", "cubeb tail pepper": "Spices, pepper, black",
    "cumin": "Spices, cumin seed", "cumin seeds": "Spices, cumin seed", "garlic powder": "Spices, garlic powder",
    "granulated garlic": "Spices, garlic powder", "onion powder": "Spices, onion powder",
    "dried oregano": "Spices, oregano, dried", "mexican oregano": "Spices, oregano, dried",
    "smoked paprika": "Spices, paprika", "paprika": "Spices, paprika", "chili powder": "Spices, chili powder",
    "kashmiri chili powder": "Spices, paprika", "ancho chili powder": "Spices, chili powder", "guajillo chile powder": "Spices, chili powder",
    "calabrian chili powder": "Spices, pepper, red or cayenne", "cayenne pepper": "Spices, pepper, red or cayenne",
    "red pepper flakes": "Spices, pepper, red or cayenne", "chinese red chili flakes": "Chinese chili flakes",
    "thai chili flakes": "Chinese chili flakes", "gochugaru": "Chinese chili flakes", "aleppo pepper": "Aleppo pepper",
    "harissa powder": "Spices, chili powder", "ground harissa": "Spices, chili powder",
    "turmeric powder": "Spices, turmeric, ground", "garam masala": "Garam masala", "curry powder": "Spices, curry powder",
    "bay leaves": "Spices, bay leaf", "ground coriander": "Spices, coriander seed", "coriander seeds": "Spices, coriander seed",
    "ground cinnamon": "Spices, cinnamon, ground", "cinnamon sticks": "Spices, cinnamon, ground",
    "nutmeg": "Spices, nutmeg, ground", "mace": "Spices, mace, ground", "allspice": "Spices, allspice, ground",
    "whole cloves": "Spices, cloves, ground", "ground clove": "Spices, cloves, ground", "star anise": "Spices, anise seed",
    "fennel seeds": "Spices, fennel seed", "mustard seeds": "Spices, mustard seed, ground", "black mustard seeds": "Spices, mustard seed, ground",
    "fenugreek seeds": "Spices, fenugreek seed", "celery seeds": "Spices, celery seed", "celery powder": "Spices, celery seed",
    "nigella seeds": "Spices, cumin seed", "black cardamom": "Spices, cardamom", "asafetida": "Spices, garlic powder",
    "saffron": "Spices, saffron", "sumac": "Sumac", "za'atar": "Za'atar",
    "dried dill": "Spices, dill weed, dried", "dried thyme": "Spices, thyme, dried", "dried sage": "Spices, sage, ground",
    "dried parsley": "Spices, parsley, dried", "dried mint": "Spearmint, fresh", "dried herbs": "Spices, oregano, dried",
    "italian seasoning": "Spices, oregano, dried", "chinese five spice": "Spices, anise seed", "ground ginger": "Spices, ginger, ground",
    "cajun seasoning": "Cajun seasoning", "taco seasoning": "Taco seasoning", "homemade taco seasoning": "Taco seasoning",
    "adobo seasoning": "Spices, garlic powder", "jollof spice mix": "Spices, curry powder", "kofta spice mix": "Spices, curry powder",
    "spice rub of choice": "Spices, chili powder", "whole dried spices": "Spices, cumin seed",
    "furikake rice seasoning": "Furikake", "poppy seeds": "Spices, poppy seed",
    # chiles, peppers
    "jalapeños": "Peppers, jalapeno, raw", "pickled jalapeños": "Peppers, jalapeno, canned, solids and liquids",
    "serrano peppers": "Peppers, serrano, raw", "habanero peppers": "Peppers, hot chili, red, raw",
    "scotch bonnets": "Peppers, hot chili, red, raw", "ghost pepper": "Peppers, hot chili, red, raw",
    "thai chilies": "Peppers, hot chili, red, raw", "red thai chiles": "Peppers, hot chili, red, raw",
    "green thai chile": "Peppers, hot chili, green, raw", "birds eye green chilies": "Peppers, hot chili, green, raw",
    "green chilies": "Peppers, hot chili, green, raw", "fresno pepper": "Peppers, hot chili, red, raw",
    "chile pepper of choice": "Peppers, hot chili, red, raw", "hatch chiles": "Peppers, hot chili, green, raw",
    "roasted hatch chilies": "Peppers, hot chili, green, raw", "anaheim peppers": "Peppers, hot chili, green, raw",
    "poblano peppers": "Peppers, hot chili, green, raw",
    "dried arbol chiles": "Peppers, hot chili, red, raw", "dried chinese red chiles": "Chinese chili flakes",
    "dried bird's eye chiles": "Chinese chili flakes", "ancho chiles": "Peppers, ancho, dried", "ancho peppers": "Peppers, ancho, dried",
    "guajillo peppers": "Peppers, ancho, dried", "pasilla chiles": "Peppers, pasilla, dried", "dried chipotle pepper": "Peppers, ancho, dried",
    "chipotles in adobo": "Chipotles in adobo", "calabrian chilies": "Calabrian chilies in oil",
    "bell peppers": "Peppers, sweet, red, raw", "red bell peppers": "Peppers, sweet, red, raw",
    "green bell peppers": "Peppers, sweet, green, raw", "yellow bell peppers": "Peppers, sweet, yellow, raw",
    "peppers": "Peppers, sweet, red, raw", "roasted peppers": "Peppers, sweet, red, canned, solids and liquids",
    "pepperoncini peppers": "Peppers, hot pickled, canned", "hot cherry peppers": "Peppers, hot pickled, canned",
    "peppadew peppers": "Peppers, hot pickled, canned", "hot & sweet peppers": "Peppers, hot pickled, canned",
    # vegetables
    "tomatoes": "Tomatoes, red, ripe, raw, year round average", "roma tomatoes": "Tomatoes, red, ripe, raw, year round average",
    "plum tomatoes": "Tomatoes, red, ripe, raw, year round average", "heirloom tomato": "Tomatoes, red, ripe, raw, year round average",
    "cherry tomatoes": "Tomatoes, red, ripe, raw, year round average", "cherry tomato juices": "Tomatoes, red, ripe, raw, year round average",
    "whole peeled tomatoes": "Tomatoes, red, ripe, canned, packed in tomato juice",
    "crushed tomatoes": "Tomatoes, crushed, canned", "diced tomatoes": "Tomatoes, red, ripe, canned, packed in tomato juice",
    "tomato paste": "Tomato products, canned, paste, without salt added (Includes foods for USDA's Food Distribution Program)", "tomato puree": "Tomato products, canned, puree, without salt added",
    "tomato sauce": "Tomato products, canned, sauce", "tomatillos": "Tomatillos, raw",
    "lettuce": "Lettuce, cos or romaine, raw", "romaine lettuce": "Lettuce, cos or romaine, raw",
    "iceberg lettuce": "Lettuce, iceberg (includes crisphead types), raw", "bib lettuce": "Lettuce, butterhead (includes boston and bibb types), raw",
    "mixed greens": "Lettuce, green leaf, raw", "arugula": "Arugula, raw", "spinach": "Spinach, raw", "kale": "Kale, raw",
    "cabbage": "Cabbage, raw", "green cabbage": "Cabbage, raw", "purple cabbage": "Cabbage, red, raw",
    "napa cabbage": "Cabbage, chinese (pe-tsai), raw", "bok choy": "Cabbage, chinese (pak-choi), raw",
    "chinese broccoli": "Broccoli, chinese, cooked", "broccoli": "Broccoli, raw", "broccolini": "Broccoli, raw",
    "baby broccoli": "Broccoli, raw", "broccoli rabe": "Broccoli raab, raw", "cauliflower": "Cauliflower, raw",
    "carrots": "Carrots, raw", "celery": "Celery, raw", "chinese celery": "Celery, raw", "cucumbers": "Cucumber, with peel, raw",
    "zucchini": "Squash, summer, zucchini, includes skin, raw", "yellow squash": "Squash, summer, all varieties, raw",
    "eggplant": "Eggplant, raw", "asian eggplants": "Eggplant, raw", "asparagus": "Asparagus, raw",
    "green beans": "Beans, snap, green, raw", "snow peas": "Peas, edible-podded, raw",
    "peas": "Peas, green, frozen, unprepared (Includes foods for USDA's Food Distribution Program)",
    "green peas": "Peas, green, frozen, unprepared (Includes foods for USDA's Food Distribution Program)",
    "frozen peas": "Peas, green, frozen, unprepared (Includes foods for USDA's Food Distribution Program)",
    "corn": "Corn, sweet, yellow, raw", "corn ear": "Corn, sweet, yellow, raw", "frozen corn": "Corn, sweet, yellow, raw",
    "edamame": "Edamame, frozen, unprepared", "brussel sprouts": "Brussels sprouts, raw", "brussels sprouts": "Brussels sprouts, raw",
    "mushrooms": "Mushrooms, white, raw", "shiitake mushrooms": "Mushrooms, shiitake, raw",
    "radishes": "Radishes, raw", "daikon radish": "Radishes, oriental, raw", "bean sprouts": "Mung beans, mature seeds, sprouted, raw",
    "bamboo shoots": "Bamboo shoots, canned, drained solids", "fennel": "Fennel, bulb, raw", "green papaya": "Papayas, raw",
    "potatoes": "Potatoes, flesh and skin, raw", "russet potatoes": "Potatoes, russet, flesh and skin, raw (Includes foods for USDA's Food Distribution Program)",
    "yukon gold potatoes": "Potatoes, flesh and skin, raw", "red potatoes": "Potatoes, red, flesh and skin, raw",
    "sweet potatoes": "Sweet potato, raw, unprepared (Includes foods for USDA's Food Distribution Program)",
    "mashed potatoes": "Potatoes, mashed, home-prepared, whole milk and butter added",
    "frozen fries": "Frozen french fries", "french fries": "Frozen french fries", "frozen tater tots": "Potato puffs, frozen, unprepared",
    "green plantains": "Plantains, green, raw", "pickled beets": "Beets, pickled, canned, solids and liquids",
    "pickles": "Pickles, cucumber, dill or kosher dill", "dill pickles": "Pickles, cucumber, dill or kosher dill",
    "pickled carrots": "Carrots, raw", "pickled daikon & carrots": "Radishes, oriental, raw", "pickled cabbage": "Cabbage, raw",
    "kimchi": "Kimchi", "olives": "Olives, ripe, canned (small-extra large)", "black olives": "Olives, ripe, canned (small-extra large)",
    "capers": "Capers, canned", "avocados": "Avocados, raw, all commercial varieties",
    "raw vegetables": "Carrots, raw", "roasted vegetables": "Squash, summer, zucchini, includes skin, raw",
    "sautéed vegetables": "Squash, summer, zucchini, includes skin, raw", "vegetable scraps": None,
    "wakame seaweed": "Seaweed, wakame, raw", "kombu": "Seaweed, kelp, raw", "seaweed handroll sheets": "Seaweed, laver, raw",
    "hominy": "Hominy, canned, white",
    # fruit
    "lemon juice": "Lemon juice, raw", "lime juice": "Lime juice, raw", "lemons": "Lemons, raw, without peel",
    "limes": "Limes, raw", "lime wedges": "Limes, raw", "lemon zest": "Lemon peel, raw", "lime zest": "Lemon peel, raw",
    "orange zest": "Orange peel, raw", "orange juice": "Orange juice, raw (Includes foods for USDA's Food Distribution Program)",
    "citrus slices": "Lemons, raw, without peel", "apples": "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    "asian pear": "Pears, asian, raw", "bananas": "Bananas, raw", "strawberries": "Strawberries, raw", "watermelon": "Watermelon, raw",
    "pomegranate seeds": "Pomegranates, raw", "dried pomegranate seeds": "Pomegranates, raw", "medjool dates": "Dates, medjool",
    "golden raisins": "Raisins, golden, seedless", "mixed dried fruit": "Raisins, golden, seedless",
    "coconut": "Nuts, coconut meat, raw", "coconut flakes": "Nuts, coconut meat, dried (desiccated), not sweetened",
    "toasted coconut powder": "Coconut powder, toasted", "applesauce": "Applesauce, canned, unsweetened, without added ascorbic acid (Includes foods for USDA's Food Distribution Program)",
    "jam": "Jams and preserves", "tamarind puree": "Tamarind puree",
    # dairy, eggs
    "eggs": "Egg, whole, raw, fresh", "egg yolks": "Egg, yolk, raw, fresh", "egg whites": "Egg, white, raw, fresh",
    "hard-boiled eggs": "Egg, whole, cooked, hard-boiled",
    "milk": "Milk, whole, 3.25% milkfat, with added vitamin D", "whole milk": "Milk, whole, 3.25% milkfat, with added vitamin D",
    "skim milk": "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)",
    "evaporated milk": "Milk, canned, evaporated, with added vitamin D and without added vitamin A",
    "low-fat evaporated milk": "Milk, canned, evaporated, nonfat, with added vitamin A and vitamin D",
    "heavy cream": "Cream, fluid, heavy whipping", "sour cream": "Cream, sour, cultured", "low-fat sour cream": "Sour cream, reduced fat",
    "crema": "Mexican crema", "yogurt": "Yogurt, plain, whole milk", "whole milk yogurt": "Yogurt, plain, whole milk",
    "greek yogurt": "Yogurt, Greek, plain, whole milk", "yogurt sauce": "Yogurt, Greek, plain, whole milk",
    "cream cheese": "Cream cheese, full fat, block", "ricotta": "Cheese, ricotta, whole milk", "farmers cheese": "Cheese, cottage, creamed, large or small curd",
    "cheese": "Cheese, cheddar", "cheddar": "Cheese, cheddar", "white sharp cheddar": "Cheese, cheddar",
    "cooper sharp": "Cheese, pasteurized process, American, fortified with vitamin D",
    "american cheese": "Cheese, pasteurized process, American, fortified with vitamin D",
    "low-fat american cheese": "Low-fat American cheese", "cheese wiz": "Cheese sauce (Cheez Whiz)",
    "parmigiano reggiano": "Parmigiano Reggiano", "parmesan": "Parmigiano Reggiano", "pecorino romano": "Pecorino Romano",
    "feta": "Cheese, feta", "queso fresco": "Cheese, fresh, queso fresco", "cotija cheese": "Cheese, mexican, queso cotija",
    "quesito": "Cheese, fresh, queso fresco", "queso de freir": "Queso de freir", "mexican manchego": "Mexican manchego",
    "low-moisture mozzarella": "Cheese, mozzarella, whole milk, low moisture", "fresh mozzarella": "Cheese, mozzarella, whole milk",
    "mozzarella pearls": "Cheese, mozzarella, whole milk", "provolone": "Cheese, provolone", "picante provolone": "Cheese, provolone",
    "monterrey jack cheese": "Cheese, monterey", "monterey jack": "Cheese, monterey", "pepper jack cheese": "Cheese, monterey",
    "colby jack cheese": "Cheese, colby", "chipotle gouda": "Cheese, gouda", "gruyere": "Cheese, gruyere", "comte": "Cheese, gruyere",
    "emmental": "Cheese, swiss", "swiss": "Cheese, swiss", "havarti": "Cheese, muenster", "blue cheese": "Cheese, blue",
    "goat cheese": "Cheese, goat, soft type", "paneer": "Paneer", "white cheddar powder": "Cheese, cheddar",
    # meat
    "chicken breasts": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    "chicken tenders": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    "chicken tenderloins": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    "chicken thighs": "Chicken, thigh, boneless, skinless, raw", "chicken drumsticks": "Chicken, broilers or fryers, drumstick, meat and skin, raw",
    "whole chicken": "Chicken, broilers or fryers, meat and skin, raw", "chicken": "Chicken, broilers or fryers, meat and skin, raw",
    "cooked chicken": "Chicken, broilers or fryers, breast, meat only, cooked, roasted",
    "grilled chicken": "Chicken, broilers or fryers, breast, meat only, cooked, roasted",
    "cooked chicken cutlet": "Chicken, broilers or fryers, breast, meat only, cooked, fried",
    "chicken skins": "Chicken, broilers or fryers, skin only, raw", "chicken carcass": None,
    "ground beef": "Beef, ground, 80% lean meat / 20% fat, raw", "80/20 ground beef": "Beef, ground, 80% lean meat / 20% fat, raw",
    "85/15 ground beef": "Beef, ground, 85% lean meat / 15% fat, raw (Includes foods for USDA's Food Distribution Program)", "93/7 ground beef": "Beef, ground, 93% lean meat / 7% fat, raw",
    "ground meat": "Beef, ground, 80% lean meat / 20% fat, raw", "meat": "Beef, ground, 80% lean meat / 20% fat, raw",
    "ground bison": "Bison, ground, raw", "ground turkey": "Turkey, Ground, raw", "ground lamb": "Lamb, ground, raw",
    "ground pork": "Pork, fresh, ground, raw",
    "steak of choice": "Beef, top sirloin steak, raw", "flank, skirt, or flatiron steak": "Beef, flank, steak, boneless, choice, raw",
    "flat iron steak": "Beef, flank, steak, boneless, choice, raw", "ribeye": "Beef, ribeye, steak, boneless, choice, raw",
    "beef sirloin": "Beef, top sirloin steak, raw", "chuck roast": "Beef, chuck, roast, boneless, choice, raw",
    "beef chuck": "Beef, chuck, roast, boneless, choice, raw", "braised beef": "Beef, chuck, roast, boneless, choice, raw",
    "braised meat": "Beef, chuck, roast, boneless, choice, raw", "beef cheeks": "Beef, chuck, roast, boneless, choice, raw",
    "oxtails": "Beef, chuck, roast, boneless, choice, raw",
    "cross-cut short ribs": "Beef short ribs",
    "english cut short ribs": "Beef short ribs",
    "venison shoulder": "Game meat, deer, raw", "lamb shoulder": "Lamb, shoulder, arm, separable lean and fat, trimmed to 1/4\" fat, choice, raw",
    "lamb stew meat": "Lamb, shoulder, arm, separable lean and fat, trimmed to 1/4\" fat, choice, raw",
    "lamb chops": "Lamb, shoulder, arm, separable lean and fat, trimmed to 1/4\" fat, choice, raw",
    "pork belly": "Pork, fresh, belly, raw", "pork shoulder": "Pork, fresh, shoulder, whole, separable lean and fat, raw",
    "braised pork": "Pork, fresh, shoulder, whole, separable lean and fat, raw",
    "pork chops": "Pork, fresh, loin, whole, separable lean and fat, raw", "boneless pork loin": "Pork, fresh, loin, whole, separable lean and fat, raw",
    "meat cutlets": "Pork, fresh, loin, whole, separable lean and fat, raw", "protein of choice": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    "bacon": "Pork, cured, bacon, unprepared", "bacon bits": "Pork, cured, bacon, cooked, baked",
    "ham": "Ham, sliced, regular (approximately 11% fat)", "deli ham": "Ham, sliced, regular (approximately 11% fat)",
    "rosemary ham": "Ham, sliced, regular (approximately 11% fat)", "country ham": "Ham, sliced, regular (approximately 11% fat)",
    "cooked prosciutto": "Ham, sliced, regular (approximately 11% fat)", "prosciutto": "Prosciutto", "guanciale": "Guanciale",
    "salami": "Salami, Italian, pork", "pepperoni": "Pepperoni, beef and pork, sliced", "mortadella": "Mortadella",
    "soppressata": "Soppressata", "fennel soppressata": "Soppressata", "chorizo": "Chorizo, Mexican raw",
    "italian sausage": "Sausage, Italian, pork, mild, raw", "hot italian sausages": "Sausage, Italian, pork, mild, raw",
    "sausage": "Sausage, Italian, pork, mild, raw", "andouille sausages": "Sausage, Italian, pork, mild, raw",
    "sliced turkey": "Ham, sliced, regular (approximately 11% fat)",
    "turkey": "Turkey, whole, meat and skin, raw", "turkey trimmings & backbone": None, "bones": None,
    # seafood
    "shrimp": "Crustaceans, shrimp, raw", "jumbo shrimp": "Crustaceans, shrimp, raw", "dried shrimp": "Crustaceans, shrimp, raw",
    "salmon": "Fish, salmon, Atlantic, farmed, raw", "smoked salmon": "Fish, salmon, chinook, smoked",
    "cod": "Fish, cod, Atlantic, raw", "white fish of choice": "Fish, cod, Atlantic, raw",
    "tuna": "Fish, tuna, light, canned in water, drained solids", "anchovies": "Fish, anchovy, european, canned in oil, drained solids",
    "live mussels": "Mollusks, mussel, blue, raw", "crayfish powder": "Crayfish powder",
    # plant protein, legumes
    "tofu": "Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)",
    "firm tofu": "Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)",
    "black beans": "Beans, black, mature seeds, canned, low sodium", "dried black beans": "Beans, black, mature seeds, raw",
    "pinto beans": "Beans, pinto, canned, drained solids", "beans": "Beans, pinto, canned, drained solids",
    "butter beans": "Lima beans, large, mature seeds, canned", "chickpeas": "Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained solids",
    "refried black beans": "Refried beans", "lentils": "Lentils, raw", "rice & beans": "Rice, white, long-grain, regular, cooked, enriched, with salt",
    "hummus": "Hummus, commercial", "roasted red pepper hummus": "Hummus, commercial",
    # grains, pasta, flour
    "flour": "Wheat flour, white, all-purpose, enriched, unbleached", "all-purpose flour": "Wheat flour, white, all-purpose, enriched, unbleached",
    "bread flour": "Wheat flour, white, bread, enriched", "whole wheat flour": "Wheat flour, whole-grain (Includes foods for USDA's Food Distribution Program)",
    "durum flour": "Semolina, enriched", "buckwheat flour": "Buckwheat flour, whole-groat", "keto flour": "Wheat flour, whole-grain (Includes foods for USDA's Food Distribution Program)",
    "cornstarch": "Cornstarch", "corn starch": "Cornstarch", "cornstarch slurry": "Cornstarch", "potato starch": "Potato starch",
    "cornmeal": "Cornmeal, whole-grain, yellow", "dried polenta": "Cornmeal, whole-grain, yellow",
    "rice": "Rice, white, long-grain, regular, raw, enriched", "white rice": "Rice, white, long-grain, regular, raw, enriched",
    "long grain rice": "Rice, white, long-grain, regular, raw, enriched", "jasmine rice": "Rice, white, long-grain, regular, raw, enriched",
    "basmati rice": "Rice, white, long-grain, regular, raw, enriched", "arborio rice": "Rice, white, medium-grain, raw, enriched",
    "sushi rice": "Rice, white, short-grain, raw, unenriched", "short-grain rice": "Rice, white, short-grain, raw, unenriched",
    "brown rice": "Rice, brown, long-grain, raw (Includes foods for USDA's Food Distribution Program)",
    "cooked rice": "Rice, white, long-grain, regular, cooked, enriched, with salt", "mexican rice": "Rice, white, long-grain, regular, cooked, enriched, with salt",
    "pasta": "Pasta, dry, enriched", "dried pasta": "Pasta, dry, enriched", "short pasta of choice": "Pasta, dry, enriched",
    "spaghetti": "Pasta, dry, enriched", "rigatoni": "Pasta, dry, enriched", "fusili": "Pasta, dry, enriched", "orzo": "Pasta, dry, enriched",
    "dried macaroni noodles": "Pasta, dry, enriched", "whole wheat spaghetti": "Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)",
    "egg noodles": "Noodles, egg, dry, enriched", "noodles": "Noodles, egg, dry, enriched", "chinese wheat noodles": "Noodles, egg, dry, enriched",
    "ramen noodles": "Ramen noodles, fresh", "vite ramen": "Instant ramen", "lo mein noodles": "Lo mein noodles",
    "wide rice noodles": "Rice noodles, dry", "flat rice noodles": "Rice noodles, dry", "asian rice noodles": "Rice noodles, dry",
    "gnocchi": "Gnocchi, shelf-stable", "rice cakes": "Tteok (rice cakes)",
    # breads, wraps
    "brioche buns": "Brioche bun", "brioche bun": "Brioche bun", "potato bun": "Bread, potato", "potato bread": "Bread, potato",
    "hamburger buns": "Rolls, hamburger or hotdog, plain", "sandwich buns": "Rolls, hamburger or hotdog, plain",
    "sesame seed bun": "Rolls, hamburger or hotdog, plain", "sesame roll": "Rolls, hamburger or hotdog, plain",
    "hoagie rolls": "Hoagie roll", "bakery sub roll": "Hoagie roll", "homemade hoagie": "Hoagie roll", "cubano roll": "Hoagie roll",
    "bolillo": "Rolls, french", "bread roll": "Rolls, hard (includes kaiser)", "ciabatta rolls": "Rolls, french",
    "baguettes": "Bread, french or vienna (includes sourdough)", "bread": "Bread, white, commercially prepared (includes soft bread crumbs)",
    "sandwich bread": "Bread, white, commercially prepared (includes soft bread crumbs)", "grain bread": "Bread, whole-wheat, commercially prepared",
    "shokupan": "Shokupan", "focaccia": "Bread, Italian", "pide (turkish bread)": "Bread, Italian",
    "pita bread": "Bread, pita, white, enriched", "lebanese style pita": "Bread, pita, white, enriched", "10\" pita wraps": "Bread, pita, white, enriched",
    "flatbreads": "Bread, pita, white, enriched", "lavash bread": "Lavash", "naan": "Naan", "roti flatbreads": "Roti",
    "paratha flatbreads": "Paratha", "bagels": "Bagels, plain, enriched, with calcium propionate (includes onion, poppy, sesame)",
    "english muffins": "English muffins, plain, enriched, without calcium propionate(includes sourdough)",
    "corn tortillas": "Tortillas, ready-to-bake or -fry, corn", "tortillas": "Tortillas, ready-to-bake or -fry, flour, refrigerated",
    "flour tortillas": "Tortillas, ready-to-bake or -fry, flour, refrigerated", "large 12\" flour tortillas": "Tortillas, ready-to-bake or -fry, flour, refrigerated",
    "whole wheat tortilla": "Tortillas, ready-to-bake or -fry, flour, refrigerated", "spinach wrap": "Tortillas, ready-to-bake or -fry, flour, refrigerated",
    "keto flour tortillas": "Low-carb tortilla", "high protein flour tortilla wraps": "High-protein tortilla", "high protein tortilla wrap": "High-protein tortilla",
    "tostadas": "Taco shells, baked", "hard taco shell": "Taco shells, baked", "taco shells": "Taco shells, baked",
    "tortilla chips": "Snacks, tortilla chips, plain, white corn, salted", "tortilla strips": "Snacks, tortilla chips, plain, white corn, salted",
    "frito corn chips": "Snacks, corn-based, extruded, chips, plain", "crackers": "Crackers, saltines (includes oyster, soda, soup)",
    "croutons": "Croutons, plain", "breadcrumbs": "Bread, crumbs, dry, grated, plain", "bread crumbs": "Bread, crumbs, dry, grated, plain",
    "panko bread crumbs": "Panko", "panko breadcrumbs": "Panko", "gyoza wrappers": "Gyoza wrappers", "rice paper wrapper": "Rice paper",
    "bao bun": "Bao bun", "arepa choclo": "Arepa de choclo", "yeast": "Leavening agents, yeast, baker's, active dry",
    "instant yeast": "Leavening agents, yeast, baker's, active dry", "baking powder": "Leavening agents, baking powder, double-acting, sodium aluminum sulfate",
    "baking soda": "Leavening agents, baking soda", "diastatic malt powder": "Diastatic malt powder", "xanthun gum": "Xanthan gum",
    # sauces, condiments
    "mayonnaise": "Salad dressing, mayonnaise, regular", "kewpie mayo": "Kewpie mayonnaise",
    "ketchup": "Catsup", "mustard": "Mustard, prepared, yellow", "yellow mustard": "Mustard, prepared, yellow",
    "dijon mustard": "Mustard, prepared, yellow", "brown mustard": "Mustard, prepared, yellow", "karashi mustard": "Mustard, prepared, yellow",
    "soy sauce": "Soy sauce made from soy and wheat (shoyu)", "light soy sauce": "Soy sauce made from soy and wheat (shoyu)",
    "dark soy sauce": "Soy sauce made from soy and wheat (shoyu)", "thai black soy sauce": "Soy sauce made from soy and wheat (shoyu)",
    "fish sauce": "Fish sauce", "oyster sauce": "Oyster sauce", "hoisin": "Sauce, hoisin, ready-to-serve", "hoison": "Sauce, hoisin, ready-to-serve",
    "worcestershire sauce": "Sauce, worcestershire", "hot sauce": "Hot sauce", "louisiana style hot sauce": "Hot sauce",
    "chipotle hot sauce": "Hot sauce", "poblano hot sauce": "Hot sauce", "buffalo sauce": "Hot sauce",
    "sriracha": "Sauce, hot chile, sriracha", "sambal": "Chili garlic sauce", "chili garlic paste": "Chili garlic sauce",
    "gochujang": "Gochujang", "harissa paste": "Harissa paste", "red curry paste": "Red curry paste",
    "massaman curry paste": "Massaman curry paste", "japanese curry cube": "Japanese curry roux", "achiote paste": "Achiote paste",
    "miso paste": "Miso paste", "ponzu": "Ponzu", "maggi seasoning": "Maggi seasoning", "tonkatsu sauce": "Tonkatsu sauce",
    "lee kum kee black pepper sauce": "Black pepper sauce", "browning sauce": "Browning sauce",
    "vinegar": "Vinegar, distilled", "white vinegar": "Vinegar, distilled", "rice vinegar": "Rice vinegar",
    "red wine vinegar": "Vinegar, red wine", "apple cider vinegar": "Vinegar, cider", "balsamic vinegar": "Vinegar, balsamic",
    "chinese black vinegar": "Chinese black vinegar", "pickle juice": "Vinegar, distilled",
    "salsa": "Salsa", "salsa verde": "Sauce, salsa, verde, ready-to-serve", "pico de gallo": "Pico de gallo",
    "enchilada sauce": "Sauce, enchilada, red, mild, ready to serve", "green enchilada sauce": "Sauce, salsa, verde, ready-to-serve",
    "green chile sauce": "Sauce, salsa, verde, ready-to-serve", "marinara": "Sauce, pasta, spaghetti/marinara, ready-to-serve",
    "pesto": "Sauce, pesto, ready-to-serve, refrigerated", "barbecue sauce": "Sauce, barbecue", "ranch": "Salad dressing, ranch dressing, regular",
    "tahini sauce": "Tahini", "muhammara": "Muhammara", "pomegranate molasses": "Pomegranate molasses",
    "hot pepper spread": "Hot pepper spread", "roasted red pepper condiment": "Roasted red pepper condiment",
    "onion confit condiment": "Onion confit", "peanut butter": "Peanut butter, smooth style, without salt",
    # stocks
    "chicken broth": "Soup, chicken broth, ready-to-serve", "chicken stock": "Soup, stock, chicken, home-prepared",
    "broth": "Soup, chicken broth, ready-to-serve", "stock": "Soup, chicken broth, ready-to-serve",
    "beef broth": "Soup, stock, beef, home-prepared", "chicken bouillon": "Chicken bouillon paste",
    "chicken bouillon powder": "Soup, chicken broth or bouillon, dry", "beef bouillon paste": "Beef bouillon paste",
    "mushroom better than bouillon": "Better Than Bouillon, mushroom", "dashi powder": "Dashi powder", "bonito flakes": "Bonito flakes",
    # sweeteners
    "sugar": "Sugars, granulated", "cane sugar": "Sugars, granulated", "brown sugar": "Sugars, brown",
    "demerara sugar": "Sugars, brown", "powdered sugar": "Sugars, powdered", "palm sugar": "Palm sugar",
    "honey": "Honey", "hot honey": "Honey", "maple syrup": "Syrups, maple", "agave syrup": "Syrups, maple",
    "vanilla extract": "Vanilla extract", "chocolate": "Chocolate, dark, 60-69% cacao solids",
    "unsweetened chocolate": "Baking chocolate, unsweetened, squares", "cocoa nibs": "Baking chocolate, unsweetened, squares",
    "protein bars": "Protein bar",
    # nuts, seeds
    "sesame seeds": "Seeds, sesame seeds, whole, dried", "black sesame seeds": "Seeds, sesame seeds, whole, dried",
    "peanuts": "Peanuts, all types, raw", "almonds": "Nuts, almonds", "walnuts": "Nuts, walnuts, english",
    "cashews": "Nuts, cashew nuts, raw", "pecans": "Nuts, pecans", "pine nuts": "Nuts, pine nuts, dried",
    "pepitas": "Seeds, pumpkin and squash seed kernels, dried", "nuts": "Nuts, almonds",
    "coconut milk": "Coconut milk, canned", "coconut cream": "Nuts, coconut cream, raw (liquid expressed from grated meat)",
    # alcohol
    "white wine": "Alcoholic beverage, wine, table, white", "red wine": "Alcoholic beverage, wine, table, red",
    "shaoxing wine": "Shaoxing wine", "sake": "Alcoholic beverage, rice (sake)", "mirin": "Mirin",
    "beer": "Alcoholic beverage, beer, regular, all", "light beer": "Alcoholic beverage, beer, light", "lager beer": "Alcoholic beverage, beer, regular, all",
    "belgian ale": "Alcoholic beverage, beer, regular, all", "vodka": "Alcoholic beverage, distilled, vodka, 80 proof",
    "whiskey": "Alcoholic beverage, distilled, whiskey, 86 proof", "brandy": "Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 80 proof",
    # not food / too vague
    "parchment paper": None, "9x13 baking dish": None, "aromatics": None, "chopped aromatics": None,
}
